language: golang

go:
  - 1.x
  - "1.15"
  - 1.15.x
  - master

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}
    - REPO=aditya109/test-cicd

services:
  - docker

script:
  - docker build --tag $REPO:$COMMIT -f Dockerfile .
  - docker-compose up

