language: node_js
node_js: 
- 11.6.0
cache: npm

# before_install:
# install:
# before_script:
# script:
# after_success:
# after_failure:
# before_deploy:
# deploy:
# after_deploy:

install:
  - yarn ci

script: 
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master