name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t test-cicd .
      - name: Tags
        run: |
          docker tag test-cicd ${{ secrets.DOCKER_USER }}/test-cicd:${{ github.sha }}
          docker tag test-cicd ${{ secrets.DOCKER_USER }}/test-cicd:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/test-cicd:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/test-cicd:latest

